name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "483263f2425d4b34b2c7bc8f012a8736" },
  { binding = "SHARE", id = "1f38210ad8d0400abc3f2b4b3de8e4ef" }
]

routes = [
  { pattern = "md.victorcv.dpdns.org/*", zone_name = "victorcv.dpdns.org" }
]
